services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shop_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  inventory-service:
    build: ./inventory-service
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/shop_db
    depends_on:
      - postgres

  history-service:
    build: ./history-service
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/shop_db
    depends_on:
      - postgres

volumes:
  postgres_data:
